language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - "/^issue.*$/"
  - /^greenkeeper/.*$/
node_js:
- '6'
os:
- linux
- osx
dist: trusty
osx_image: xcode9
before_install:
- if [[ $TRAVIS_NODE_VERSION == "8" ]]; then npm install -g npm@4; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi
- git clone https://github.com/IBM-Swift/Package-Builder.git
- npm i -g makeshift
script:
- osName="linux"
- hubVersion="2.2.9"
- hubBin="hub-linux-amd64-${hubVersion}"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then osName="osx"; hubBin="hub-darwin-amd64-${hubVersion}"; fi
- hubUrl="https://github.com/github/hub/releases/download/v${hubVersion}/${hubBin}.tgz"
- curl -Ls $hubUrl | tar zxv
- export PATH=$(pwd)/${hubBin}/bin:$PATH
- export projectFolder=`pwd`
- projectName="$(basename $projectFolder)"
- export SWIFT_SNAPSHOT=swift-4.0
- source ./Package-Builder/install-swift.sh
- #if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then npm run testsdkgen; fi
- #if [[ $TRAVIS_EVENT_TYPE != "cron" ]]; then npm run coverage && npm run report-coverage; fi
jobs:
  include:
  - stage: Review
    node_js: '6'
    script: "./review.sh"
    if: type = push AND branch = develop
  - stage: Releases
    language: ruby
    script: "./release.sh"
    if: type = push AND branch = master
env:
  global:
  - CXX=g++-4.8
